name: tukugo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.0  # For converting address text to coordinates
  flutter:
    sdk: flutter
  intl_phone_field: ^3.2.0
  go_router: ^5.2.0  
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  smooth_page_indicator: ^1.1.0  
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  dotted_border: ^2.0.0+3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^0.15.0
  shared_preferences: ^2.1.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  # flutter_lints: ^5.0.0  # Uncomment if needed

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/ProfilePic.jpg
    - assets/QR.png
    - assets/payment.png
    - assets/location.svg
    - assets/Homecenter.png
    - assets/location.png
    - assets/location_icon.png
    - assets/locationArrow.png
    - assets/vehicalselect.svg
    - assets/lovationHeader.svg
    - assets/locationArrow.svg
    - assets/locationAccess.svg
    - assets/driverprofile.svg
    - assets/flags/
    - assets/flags/english.png
    - assets/flags/arabic.png
    - assets/flags/french.png
    - assets/flags/india.png
    - assets/flags/german.png
    - assets/flags/portugues.png
    - assets/flags/turkish.png
    - assets/flags/dutch.png
    - assets/top_curve.svg
    - assets/google_icon.png
    - assets/facebook.png
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 500
       


   
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/TukugoLogo.jpg"
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21
